id: lt.medicinos.biblioteka.histopathology
canonical: https://lmb.lt/fhir/histopathology
name: LithuanianHistopathologyIG
title: "Lithuanian Histopathology FHIR Implementation Guide"
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: ci-build